### ISSUE TITLE
render_templates.sh should remove template after rendering

### ISSUE THREAD

**Issue by macropin** [panubo/bash-container#4]
render_templates function should remove the template after rendering to prevent exposing or leaving templates in deployed artefacts.

**Comment by trnubo** [comment]
This should be optional. If you are rendering a configuration file that remains in the running container the tmpl file would not cause any harm and could aid in debugging/diagnosis plus removing the template file won't decrease the size of the container since it is already running. Whether or not the template is exposed would depend on the server running in the container.

Alternatively the template will be overwritten if it doesn't have the `.tmpl` extension.

As far as implementation goes maybe `render_templates [-d] FILENAME [FILENAME...]` would be suitable.

**Comment by macropin** [comment]
The reason for not leaving templates in deployed artefacts is to prevent a recurrence of an issue we previously had with PHP templates. IIRC mod-php was complaining that the configs were invalid due to the presence of an un-rendered template in the config path.

**Comment by macropin** [comment]
I've had a change of heart on this one. I think the current mode of operation is working, and is preferable as it allows the entry point to be rerun. 

Ref eg: https://github.com/panubo/docker-php-apache/blob/main/debian11/root/entry.sh
